Add "list" to email editor elements
chamaileon-sdk/sdk-playground pull request #207
Opened 2023-02-03 10:54 UTC by ororora

[DEV-3162](https://edmdesigner.atlassian.net/browse/DEV-3162)

2023-02-03 14:31 UTC, danilovilhena approved these changes

2023-02-08 10:24 UTC, lacee677 requested changes

2023-02-08 10:24 UTC, lacee677 commented on src/components/EmailEditor/components/Elements.vue
> +		<h2>Elements </h2>
```suggestion
		<h2>Elements</h2>
```

2023-02-08 10:24 UTC, lacee677 commented on src/components/EmailEditor/store/emailEditorConfig.js
> +						text: "Double click to edit text!",
keep this as <p> </p> because otherwise you break the old text element

2023-02-08 10:24 UTC, lacee677 commented on src/components/EmailEditor/components/Elements.vue
> +				return "To enable this element, disable the title, list and paragraph elements";
```suggestion
				return "To enable this element, disable the Title, List and Paragraph elements";
```

2023-02-08 10:24 UTC, lacee677 commented on src/components/EmailEditor/components/Elements.vue
>  				return "To enable this element, disable the text element";
```suggestion
				return "To enable this element, disable the Text element";
```

2023-02-13 11:14 UTC, lacee677 approved these changes

2023-02-13 11:14 UTC, merged